# 转载指定 Youtube视频到Bilibili
# 使用前,在 Settings > Secrets 创建如下键值
# USER_CRED : (登陆设置) e.g. --username [B站用户名] --pwd [B站密码]

name: 转载视频

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Youtube / Twitch / Twitter / etc 视频链接'
        required: true
        default: ''
      opts:
        description: '转载设置，如 --tags [标签,半角逗号隔开] --thread_id [分区 id,见 README] e.g. --tags 游戏,单机 --thread_id 17'
        required: true
        default: ''
      ydl_opts:
        description: 'yt-dlp 设置，默认设置使用 aria2 下载；遇到限流可考虑添加 format=best'
        required: false
        default: 'external_downloader=aria2c'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt  
        sudo apt-get install aria2
    - name: Begin Reuploading      
      env:     
        USER_CRED : ${{ secrets.USER_CRED }}     
      run: |
        python -m bilibili_toolman $USER_CRED --http --cdn gcs --youtube "${{ github.event.inputs.url }}" ${{ github.event.inputs.opts }} --opts "${{ github.event.inputs.ydl_opts }}"
